### ISSUE TITLE
MusicBar Error Detection

### ISSUE THREAD

**Issue by bseto** [UCSolarCarTeam/Schulich-Delta-OnBoard-Media-Control#18]
MusicBar should not be created when there are no songs in the Music folder.
SongPlayer detects if the SongLoader reads no songs and does not instantiate, however, MusicBar is still instantiated, and it requires the SongPlayer. 
- [ ] Check in Main.cpp if MusicBar should be created

**Comment by ExtraGravity** [comment]
@bseto  This is fixed already right?

**Comment by bseto** [comment]
I will have to test it again. We will also have to change some behavior as I think as it sits currently, the bar is just completely removed if there are no songs. Our new expected behavior would be having the music bar report that there is no music.

**Comment by bseto** [comment]
New project should address this.
