### ISSUE TITLE
Backup/Reverse Mode. 

### ISSUE THREAD

**Issue by bseto** [UCSolarCarTeam/Schulich-Delta-OnBoard-Media-Control#27]
Right now, our backup camera is used while driving while conventionally the backup camera is used when backing up. I was thinking it might be cool to look into making a "reverse" mode where the camera can provide some feedback and insert some lines on where the predicted car will go. 

Example: http://images.dailytech.com/nimage/backup_camera_car_and_driver.jpg

**Comment by mpminardi** [comment]
How detailed do you think we would go? Would we just give general distance / draw an outline straight out the back, or would we move the prediction based on the angle of the wheels?

**Comment by bseto** [comment]
I was thinking it would be very cool if we could predict based on the angle of the wheels too.

**Comment by mpminardi** [comment]
Do we have any existing method in place to get that information?

**Comment by bseto** [comment]
Nope. I think at best we could get the speed but ya, no method of getting that information with the current car.

**Comment by mpminardi** [comment]
Okay. We could always stick an accelerometer on the steering wheel and try to get the orientation or something (or see if we already have something we are not utilizing), but that would probably be a longer term goal.

**Comment by ExtraGravity** [comment]
In New York, I had the idea of having a proximity detector, I think that would be pretty cool. For a proximity detector we could have a similar setup with the camera where we have the proximity detector in the back, we run lines to the pi in the front and connect to an SPI port. 

As for a direction, right now the wheels are done completely mechanically, so no electrical system knows anything about how the wheels are turned.

**Comment by bseto** [comment]
I think the ideas are pretty cool. However, I think making the application more stable and making a test suite will be more important. 

Closing for now.
